import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer/Footer";
import MySession from "@/components/MySession/MySession";
import MainNavbar from "@/components/NavBar/MainNavbar";

const inter = Exo({ subsets: ["latin"], variable: "--font-exo" });

export const metadata: Metadata = {
  title: "Create Fresh Cart",
  description: "Fresh Cart Generated by Mariam Gad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className={`antialiased overflow-auto`}>
        <MySession>
          <MainNavbar />
          <Toaster richColors position="top-center" />
          {children}
          <Footer />
        </MySession>
      </body>
    </html>
  );
}
